language: ruby
cache: bundler
before_install:
  - gem update --system
  - gem install bundler
deploy:
  - provider: rubygems
    gem: doxie
    email: cristiano@betta.io
    on:
      tags: true
      rvm: 2.7.1
    api_key: $RUBYGEMS_API_KEY
rvm:
  - 2.5
  - 2.6
  - 2.7
  - 2.7.1  # explicit branch used for deploying gem
  - ruby-head
  - jruby
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby
    - rvm: 2.7.1